### ISSUE TITLE
have mounted container well but i don't know how to use this.

### ISSUE THREAD

**Issue by pepya2** [instrumentisto/postfix-docker-image#11]
i have other containers having php sites, but sending mails in those containers doesn't work.. i found this postfix-docker-image hoped could solve.. i installed and is running well..

![im](https://user-images.githubusercontent.com/25289859/43901329-e60568b8-9bef-11e8-94c2-3b1306c3c6d9.png)

i dont know how i can make other containers send mail using this postfix-docker-image
any help will be appreciated.
thanks..

**Comment by tyranron** [comment]
@pepya2 your question is far beyond this repository mission. This repository provides __only raw Postfix__ Docker image without anything else. This is intended to be used as a building block for larger cloud-native mailservers installations.

Except single Postfix, mailserver often uses another bunch of software (like Dovecot, OpenDKIM, etc.), so implementation of sending mails via PHP with the only raw Postfix can be a quite tricky (because you need mail accounts and etc.).

I recommend you to use more complete and complex mailservers for your problem like [tomav/docker-mailserver](tomav/docker-mailserver) or [Mailhog](https://hub.docker.com/r/mailhog/mailhog/).

Here is a relevant article:   
https://blog.philipphauer.de/test-mail-server-php-docker-container/
