### ISSUE TITLE
where is entrypoint /init created

### ISSUE THREAD

**Issue by controlol** [instrumentisto/postfix-docker-image#15]
Hi,

I tried to create a docker image of this but updated to the latest version of debian (and therefor updating some debs) and postfix.
The build is now succesful, but /init does not exist.

I only removed the S6 portion as I don't need that.
I can't find anything that relates to /init in the dockerfile apart from the entrypoint. 

Is /init needed for the image to work?

I have the forked version on my profile.

**Comment by tyranron** [comment]
@controlol 

> Is /init needed for the image to work?

Yes. It's [installed](https://github.com/instrumentisto/postfix-docker-image/blob/58ff9f8983934d96cedb8ec3caac2af306416d94/Dockerfile.tmpl.php#L262-L276) via [`s6-overlay`](https://github.com/just-containers/s6-overlay).

> I only removed the S6 portion as I don't need that.

You _do_ need that, because it powers the container to work smoothly by performing [some init job](https://github.com/instrumentisto/postfix-docker-image/tree/58ff9f8983934d96cedb8ec3caac2af306416d94/rootfs/etc/cont-init.d) and [supervising (keeping up and running) `syslogd`](https://github.com/instrumentisto/postfix-docker-image/tree/58ff9f8983934d96cedb8ec3caac2af306416d94/rootfs/etc/services.d/syslog), which is responsible to print Postfix logs to STDERR/STDOUT, as Postfix cannot do that itself.

**Comment by controlol** [comment]
Thanks dor your response!

I thought s6 had a totally different purpose. I immediately associated it with networking because of "overlay" 😅. Thanks for telling me. I suppose I will re-add it. 

However postfix 3.4 added support for a log file which could be linked to stdout.

**Comment by tyranron** [comment]
@controlol 

> However postfix 3.4 added support for a log file which could be linked to stdout.

That's nice. Haven't played with it yet. If it works OK, then `services.d/syslog` and `syslog.conf` can be removed from the `rootfs/` as unnecessary.

But [`cont-init.d/` jobs](https://github.com/instrumentisto/postfix-docker-image/tree/58ff9f8983934d96cedb8ec3caac2af306416d94/rootfs/etc/cont-init.d) still remain very useful in context of Postfix. However, now it will be enough to have a `docker-entrypoint.sh` which does that, no need in the whole `s6-overlay`.

I'll close this. Feel free to reopen if you'll have further questions.
